name: patch

on:
  push:
    branches: ["fp"]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          path: "fp"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          path: "net"

      - name: config git
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          cd fp
          git fetch --all
          cd ../net
          git fetch --all

      - name: sync master and tags
        run: |
          cd net

          git remote add upstream https://github.com/golang/net
          git checkout master
          git pull upstream master --tags
          git push origin master --tags

      - name: patch
        run: |
          set -x

          cd net

          latest_tag="$(git describe --tags "$(git rev-list --tags --max-count=1)")"
          if [ -z "$latest_tag" ]; then
            echo "failed to get latest_tag"
            exit 1
          fi

          cd ../fp/patches
          if [ ! -f "$latest_tag.patch" ]; then

            last_patch="$(ls | sort -V | tail -1)"
            if [ -z "$last_patch" ]; then
              echo "failed to get last_patch"
              exit 1
            fi
            ln -s "$last_patch" "$latest_tag.patch"
            git add "$latest_tag.patch"
            git commit -m "chore: add $latest_tag.patch"

          fi
          cd ../../net

          git tag  | sort -V | xargs -I {} ../fp/patch.sh {} ../fp/patches/{}.patch
          git push --all origin

      - name: revision
        run: |
          # wait for `git push`
          sleep 60s
          cd fp

          [ -f revision.txt ] || touch revision.txt
          git tag  | sort -V | xargs -I {} ./revision.sh {} ./revision.txt
          git add revision.txt
          if git commit -m "update revision"; then
            git push origin fp
          fi
